import { SpecialistConfig, SpecialistId, SharedBrainProfile } from "@/types/orbit";

export const SPECIALISTS: Record<SpecialistId, SpecialistConfig> = {
  core: {
    id: "core",
    name: "Orbit Core",
    domain: "Central Orchestrator",
    tagline: "One front door, shared memory, and domain routing.",
    color: "#fbbf24", // Solar Gold
    glowColor: "rgba(251, 191, 36, 0.6)",
    orbitRadius: 0, // Center Sun
    orbitSpeed: 0,
    size: 2.5,
    features: [
      "Multi-agent intent routing via NVIDIA Nemotron",
      "Sovereign external action authorization gates",
      "Solar Dawn morning brief projection",
      "Unified Shared Brain profile access",
    ],
  },
  health: {
    id: "health",
    name: "Orbit Health",
    domain: "Nutrition & Bulk",
    tagline: "Honest macro ranges, daily totals, bulk tracking.",
    color: "#10b981", // Emerald Gaia
    glowColor: "rgba(16, 185, 129, 0.5)",
    orbitRadius: 6.2,
    orbitSpeed: 0.52,
    size: 0.95,
    features: [
      "Honest macro range estimation (calories & protein)",
      "Daily intake pacing vs 3,000-3,200 kcal bulk target",
      "High protein target: 160-180g",
      "Water and cadence reminders",
    ],
  },
  move: {
    id: "move",
    name: "Orbit Move",
    domain: "Workouts & Athletics",
    tagline: "Lifting progression, PR tracking, volleyball coordination.",
    color: "#f97316", // Rust Mars
    glowColor: "rgba(249, 115, 22, 0.5)",
    orbitRadius: 9.8,
    orbitSpeed: 0.42,
    size: 0.9,
    features: [
      "4x/week lifting split tracking",
      "Men's Volleyball game day coordination",
      "Muscle group recovery status",
      "PR and progressive overload logs",
    ],
  },
  schedule: {
    id: "schedule",
    name: "Orbit Schedule",
    domain: "Time & Calendar",
    tagline: "Google Calendar connector, free blocks, confirmed holds.",
    color: "#06b6d4", // Chrono Cyan
    glowColor: "rgba(6, 182, 212, 0.5)",
    orbitRadius: 13.8,
    orbitSpeed: 0.35,
    size: 0.95,
    features: [
      "Primary school + volleyball schedule sync",
      "Free time discovery for study sessions",
      "Strict confirm before creating or deleting events",
      "Inter-specialist schedule holds",
    ],
  },
  study: {
    id: "study",
    name: "Orbit Study",
    domain: "Academics & Learning",
    tagline: "Slide ingest, Nemotron flashcards, quiz engine.",
    color: "#38bdf8", // Sapphire Ice Giant
    glowColor: "rgba(56, 189, 248, 0.5)",
    orbitRadius: 18.2,
    orbitSpeed: 0.29,
    size: 1.15,
    features: [
      "Slide and PDF document synthesis",
      "AI flashcard generation via Nemotron-70B",
      "Spaced review and weak topic tracking",
      "Helps you learn; will not submit graded work",
    ],
  },
  wallet: {
    id: "wallet",
    name: "Orbit Wallet",
    domain: "Budget & Cashflow",
    tagline: "Monthly spending meter, expense audits, soft limits.",
    color: "#eab308", // Ringed Saturn
    glowColor: "rgba(234, 179, 8, 0.5)",
    orbitRadius: 23.0,
    orbitSpeed: 0.24,
    size: 1.35,
    features: [
      "Strict $800/month spending cap pacing",
      "Chat purchase logging and receipt analysis",
      "Soft budget context for Travel and Deals",
      "Sovereign privacy: zero external bank API sync",
    ],
  },
  deals: {
    id: "deals",
    name: "Orbit Deals",
    domain: "Student Discounts",
    tagline: "Curated .edu offers and tech hardware discounts.",
    color: "#34d399", // Emerald Moonlet
    glowColor: "rgba(52, 211, 153, 0.5)",
    orbitRadius: 2.8,
    orbitSpeed: 0.24,
    size: 0.65,
    features: [
      "On-demand .edu discount hunts",
      "Live web discovery via Tavily search",
      "Zero auto-purchase; user reviews every link",
      "Hardware and software student perks",
    ],
  },
  explore: {
    id: "explore",
    name: "Orbit Explore",
    domain: "Campus & Local Events",
    tagline: "Rochester local scene, tech meetups, hackathons.",
    color: "#a855f7", // Amethyst Aurora
    glowColor: "rgba(168, 85, 247, 0.5)",
    orbitRadius: 28.2,
    orbitSpeed: 0.19,
    size: 1.05,
    features: [
      "Curated Rochester and RIT campus shortlists",
      "AI/ML tech meetups and volleyball events",
      "Filtered signal over spam",
      "One-click calendar RSVP hold proposal",
    ],
  },
  travel: {
    id: "travel",
    name: "Orbit Travel",
    domain: "Break Flights & Logistics",
    tagline: "BOS to ROC break flight hunter, academic look-ahead.",
    color: "#0ea5e9", // Oceanic Atmosphere
    glowColor: "rgba(14, 165, 233, 0.5)",
    orbitRadius: 33.6,
    orbitSpeed: 0.16,
    size: 0.95,
    features: [
      "RIT Rochester to Boston route monitoring",
      "3-week look-ahead before university breaks",
      "Wallet $800 constraint and study conflict cross-check",
      "Zero auto-booking; strictly suggest and confirm",
    ],
  },
  career: {
    id: "career",
    name: "Orbit Career",
    domain: "Internships & Story",
    tagline: "Summer 2027 SWE/ML hunt, resume tailoring, strategy.",
    color: "#818cf8", // Cyber Carbon
    glowColor: "rgba(129, 140, 248, 0.5)",
    orbitRadius: 39.2,
    orbitSpeed: 0.13,
    size: 1.15,
    features: [
      "Summer 2027 SWE and ML internship pipeline",
      "RIT BS AI '28 resume tailoring",
      "Application draft assist with explicit user confirmation",
      "Hands proof-of-work project specs to Orbit Build",
    ],
  },
  build: {
    id: "build",
    name: "Orbit Build",
    domain: "Portfolio Projects",
    tagline: "JD to scoped technical spec, architecture, and starter code.",
    color: "#6366f1", // Cyber Moonlet
    glowColor: "rgba(99, 102, 241, 0.5)",
    orbitRadius: 2.8,
    orbitSpeed: 0.12,
    size: 0.65,
    features: [
      "Job description to scoped portfolio project generator",
      "Architecture specs, starter code, and README creation",
      "GitHub repo creation only after explicit approval",
      "Demo script generation for recruiter reviews",
    ],
  },
};

export const INITIAL_DEMO_BRAIN: SharedBrainProfile = {
  student: {
    name: "Gyan",
    university: "Rochester Institute of Technology",
    degree: "BS Artificial Intelligence",
    gradYear: "2028",
    campus: "Rochester, NY",
    homeAirport: "BOS (Boston Logan)",
    primaryCalendar: "RIT Academic & Men's Volleyball",
  },
  goals: {
    nutrition: {
      goal: "bulk",
      caloriesTarget: 3100,
      proteinTarget: 170,
    },
    workout: {
      split: "Upper / Lower 4x week",
      frequencyPerWeek: 4,
      sports: ["Men's Volleyball Club"],
    },
    wallet: {
      monthlyBudgetCap: 800,
      currency: "USD",
    },
    career: {
      targetRoles: ["Machine Learning Engineer Intern", "Systems SWE Intern"],
      targetSeason: "Summer 2027",
      skills: ["PyTorch", "C++", "Distributed Systems", "NVIDIA CUDA", "TypeScript"],
    },
  },
  activity: {
    meals: [
      {
        id: "m-1",
        name: "Morning Oats with Whey & Peanut Butter",
        caloriesMin: 680,
        caloriesMax: 740,
        proteinGrams: 48,
        time: "08:30 AM",
      },
      {
        id: "m-2",
        name: "Double Chicken Rice Bowl + Black Beans",
        caloriesMin: 850,
        caloriesMax: 920,
        proteinGrams: 64,
        time: "01:15 PM",
      },
      {
        id: "m-3",
        name: "Greek Yogurt, Berries & Honey Snack",
        caloriesMin: 320,
        caloriesMax: 360,
        proteinGrams: 26,
        time: "04:45 PM",
      },
    ],
    workouts: [
      {
        id: "w-1",
        day: "Monday",
        focus: "Heavy Upper (Bench & Rows)",
        status: "completed",
        exercises: ["Bench Press 4x6 @ 195lb", "Barbell Rows 4x8 @ 165lb", "Incline DB Press 3x10", "Cable Lateral Raises 4x15"],
      },
      {
        id: "w-2",
        day: "Tuesday",
        focus: "Lower Body (Squat & Hamstrings)",
        status: "completed",
        exercises: ["Back Squat 4x5 @ 245lb", "Romanian Deadlift 3x8 @ 205lb", "Bulgarian Split Squats 3x10", "Standing Calf Raises 4x15"],
      },
      {
        id: "w-3",
        day: "Thursday",
        focus: "Upper Hypertrophy & Arms",
        status: "upcoming",
        exercises: ["Overhead Press 4x6 @ 125lb", "Weighted Pull-ups 4x6", "Dips 3x10", "Hammer Curls 3x12"],
      },
      {
        id: "w-4",
        day: "Friday",
        focus: "Volleyball Match Preparation (Light Legs)",
        status: "upcoming",
        exercises: ["Box Jumps 4x5", "Core Anti-Rotation 3x12", "Shoulder External Rotation 3x15"],
      },
    ],
    calendar: [
      {
        id: "c-1",
        title: "CSCI 320: Principles of Data Mining",
        time: "10:00 AM - 11:15 AM",
        category: "class",
      },
      {
        id: "c-2",
        title: "CSCI 431: Introduction to Computer Vision",
        time: "02:00 PM - 03:15 PM",
        category: "class",
      },
      {
        id: "c-3",
        title: "RIT Men's Volleyball Practice",
        time: "06:00 PM - 08:00 PM",
        category: "sports",
      },
      {
        id: "c-4",
        title: "Study Block: Distributed Systems Paper Review",
        time: "08:30 PM - 10:00 PM",
        category: "study",
        isHold: true,
      },
    ],
    expenses: [
      {
        id: "e-1",
        item: "Campus Dining Meal Add-on",
        cost: 38.5,
        category: "Food",
        date: "Today",
      },
      {
        id: "e-2",
        item: "RIT Bookstore Course Supplies",
        cost: 42.15,
        category: "Academics",
        date: "Yesterday",
      },
      {
        id: "e-3",
        item: "Volleyball Tournament Travel Fund",
        cost: 65.0,
        category: "Athletics",
        date: "3 days ago",
      },
      {
        id: "e-4",
        item: "Protein Powder & Creatine Restock",
        cost: 54.99,
        category: "Health",
        date: "5 days ago",
      },
    ],
    studyDecks: [
      {
        id: "deck-1",
        course: "CSCI 431 Computer Vision",
        title: "Convolutional Filters & Feature Maps",
        cards: [
          {
            id: "card-1",
            question: "What is the primary spatial benefit of 1x1 convolutions in modern CNN architectures?",
            answer: "Channel dimension reduction (pooling across depth) with minimal computational cost and added non-linearity.",
            mastered: true,
          },
          {
            id: "card-2",
            question: "Explain the vanishing gradient remedy provided by Residual skip connections (ResNet).",
            answer: "They allow the gradient to propagate directly back through the identity shortcut: F(x) + x, preventing exponential decay.",
            mastered: false,
          },
          {
            id: "card-3",
            question: "What does the receptive field calculation depend on across successive convolutional layers?",
            answer: "Filter kernel size, stride, and dilation factor accumulated through layer depth.",
            mastered: false,
          },
        ],
      },
    ],
    careerPipeline: [
      {
        id: "job-1",
        company: "NVIDIA",
        role: "Deep Learning Systems Intern (Summer 2027)",
        stage: "resume-ready",
        matchScore: 94,
      },
      {
        id: "job-2",
        company: "Nebius AI Studio",
        role: "Inference Infrastructure Engineering Intern",
        stage: "staged",
        matchScore: 91,
      },
      {
        id: "job-3",
        company: "Redis",
        role: "Distributed Storage Intern",
        stage: "submitted",
        matchScore: 88,
      },
    ],
  },
  pendingApprovals: [
    {
      id: "auth-1",
      specialistId: "schedule",
      title: "Schedule Study Block: Distributed Systems Review",
      description: "Orbit Study proposed holding 8:30 PM - 10:00 PM tonight for CSCI 320 exam preparation. Checks confirm no volleyball match conflicts.",
      service: "Google Calendar",
      payload: {
        summary: "Study Hold: CSCI 320 Distributed Systems",
        startTime: "20:30",
        endTime: "22:00",
      },
      status: "pending",
      safetyCheck: "No conflicts detected. Post-practice cooldown respected.",
      timestamp: "10 mins ago",
    },
    {
      id: "auth-2",
      specialistId: "career",
      title: "Submit Tailored Resume to NVIDIA Deep Learning Systems",
      description: "Orbit Career has generated a tailored one-page resume highlighting CUDA kernel optimization and Redis experience for the Summer 2027 intern opening.",
      service: "Job Portal",
      payload: {
        targetCompany: "NVIDIA",
        role: "Deep Learning Systems Intern",
        resumeVariant: "RIT_AI_Gyan_NVIDIA_2027.pdf",
      },
      status: "pending",
      safetyCheck: "Confirmed 1-page compliance and honest skill representation.",
      timestamp: "1 hour ago",
    },
  ],
};
